=== rbatis/rbatis/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2017 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use it file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* |updateTemplete* | delete* |deleteTemplete* | select* | selectTemplete* | insertTemplete* )+>
        <!ATTLIST mapper
                >

        <!ELEMENT cache-ref EMPTY>
        <!ATTLIST cache-ref
                namespace CDATA #REQUIRED
                >

        <!ELEMENT cache (property*)>
        <!ATTLIST cache
                type CDATA #IMPLIED
                eviction CDATA #IMPLIED
                flushInterval CDATA #IMPLIED
                size CDATA #IMPLIED
                readOnly CDATA #IMPLIED
                blocking CDATA #IMPLIED
                >

        <!ELEMENT parameterMap (parameter+)?>
        <!ATTLIST parameterMap
                id CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT parameter EMPTY>
        <!ATTLIST parameter
                property CDATA #REQUIRED
                langType CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                mode (IN | OUT | INOUT) #IMPLIED
                resultMap CDATA #IMPLIED
                scale CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
        <!ATTLIST resultMap
                id CDATA #REQUIRED
                extends CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                >

        <!ELEMENT constructor (idArg*,arg*)>

        <!ELEMENT id EMPTY>
        <!ATTLIST id
                property CDATA #IMPLIED
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT result EMPTY>
        <!ATTLIST result
                property CDATA #IMPLIED
                langType CDATA #IMPLIED
                column CDATA #IMPLIED

                version_enable CDATA #IMPLIED
                logic_enable CDATA #IMPLIED
                logic_deleted CDATA #IMPLIED
                logic_undelete CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT idArg EMPTY>
        <!ATTLIST idArg
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                typeHandler CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT arg EMPTY>
        <!ATTLIST arg
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                typeHandler CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
        <!ATTLIST collection
                property CDATA #REQUIRED
                column CDATA #IMPLIED
                langType CDATA #IMPLIED
                ofType CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                notNullColumn CDATA #IMPLIED
                columnPrefix CDATA #IMPLIED
                resultSet CDATA #IMPLIED
                foreignColumn CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                fetchType (lazy|eager) #IMPLIED
                >

        <!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
        <!ATTLIST association
                property CDATA #REQUIRED
                column CDATA #IMPLIED
                langType CDATA #IMPLIED
                <!--jdbcType CDATA #IMPLIED-->
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                notNullColumn CDATA #IMPLIED
                columnPrefix CDATA #IMPLIED
                resultSet CDATA #IMPLIED
                foreignColumn CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                fetchType (lazy|eager) #IMPLIED
                >

        <!ELEMENT discriminator (case+)>
        <!ATTLIST discriminator
                column CDATA #IMPLIED
                langType CDATA #REQUIRED
                <!--jdbcType CDATA #IMPLIED-->
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
        <!ATTLIST case
                value CDATA #REQUIRED
                resultMap CDATA #IMPLIED
                resultType CDATA #IMPLIED
                >

        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT typeAlias EMPTY>
        <!ATTLIST typeAlias
                alias CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST select
                id CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                resultType CDATA #IMPLIED
                
               
                fetchSize CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                useCache (true|false) #IMPLIED
                
                lang CDATA #IMPLIED
                
                
                >

        <!ELEMENT selectTemplete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST selectTemplete
                id CDATA #IMPLIED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                resultType CDATA #IMPLIED


                fetchSize CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                useCache (true|false) #IMPLIED

                lang CDATA #IMPLIED


                tables CDATA #REQUIRED
                columns CDATA #IMPLIED
                wheres CDATA #IMPLIED
                >


        <!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST insert
                id CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
               
                
                useGeneratedKeys (true|false) #IMPLIED
                
                
                lang CDATA #IMPLIED
                >

        <!ELEMENT insertTemplete (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST insertTemplete
                id CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                tables CDATA #REQUIRED
                inserts CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                >

        <!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST selectKey
                resultType CDATA #IMPLIED
               
                
                
                order (BEFORE|AFTER) #IMPLIED
                
                >

        <!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST update
                id CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
               
                
                useGeneratedKeys (true|false) #IMPLIED
                
                
                lang CDATA #IMPLIED
                >
        <!ELEMENT updateTemplete (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST updateTemplete
                id CDATA #IMPLIED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                resultMap (BaseResultMap) #IMPLIED

                useGeneratedKeys (true|false) #IMPLIED


                lang CDATA #IMPLIED
                tables CDATA #REQUIRED
                sets CDATA #IMPLIED
                wheres CDATA #IMPLIED
                >

        <!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST delete
                id CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
               
                
                lang CDATA #IMPLIED
                >
        <!ELEMENT deleteTemplete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST deleteTemplete
                id CDATA #IMPLIED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED


                lang CDATA #IMPLIED
                tables CDATA #REQUIRED
                wheres CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                >
        <!-- Dynamic -->

        <!ELEMENT include (property+)?>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >

        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST sql
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>
        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== rbatis/rbatis/src/example/Example_ActivityMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://raw.githubusercontent.com/zhuxiujia/Rbatis/master/mybatis-3-mapper.dtd">
<mapper>
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
    <resultMap id="BaseResultMap">
        <id column="id" property="id"/>
        <result column="name" property="name" lang_type="string"/>
        <result column="pc_link" property="pcLink" lang_type="string"/>
        <result column="h5_link" property="h5Link" lang_type="string"/>
        <result column="remark" property="remark" lang_type="string"/>
        <result column="version" property="version" lang_type="int" version_enable="true"/>
        <result column="create_time" property="createTime" lang_type="time.Time"/>
        <result column="delete_flag" property="deleteFlag" lang_type="int" logic_enable="true" logic_undelete="1" logic_deleted="0"/>
    </resultMap>
    <!--SelectByCondition func(name *string, startTime *time.Time, endTime *time.Time, page *int, size *int) ([]Activity, error) `mapperParams:"name,startTime,endTime,page,size"`-->
    <select id="select_by_condition" resultMap="BaseResultMap">
        <bind name="pattern" value="'%' + name + '%'"/>
        select * from biz_activity
        <where>
            <if test="name != null">and name like #{pattern}</if>
            <if test="startTime != null">and create_time >= #{startTime}</if>
            <if test="endTime != null">and create_time &lt;= #{endTime}</if>
        </where>
        order by create_time desc
        <if test="page != null and size != null">limit #{page}, #{size}</if>
    </select>
    <!--int countByCondition(@Param("name")String name,@Param("startTime") Date startTime, @Param("endTime")Date endTime);-->
    <select id="countByCondition">
        select count(id) from biz_activity where delete_flag=1
        <if test="name != nil">
            and name like concat('%',#{name},'%')
        </if>
        <if test="startTime != nil">
            and create_time >= #{startTime}
        </if>
        <if test="endTime != nil">
            and create_time &lt;= #{endTime}
        </if>
    </select>
    <!--List<Activity> selectAll();-->
    <select id="selectAll">
        select * from biz_activity where delete_flag=1 order by create_time desc
    </select>
    <!--Activity selectByUUID(@Param("uuid")String uuid);-->
    <select id="selectByUUID">
        select * from biz_activity
        where uuid = #{uuid}
        and delete_flag = 1
    </select>
    <select id="selectById">
        select * from biz_activity
        where id = #{id}
        and delete_flag = 1
    </select>
    <select id="selectByIds">
        select * from biz_activity
        where delete_flag = 1
        <foreach separator="," collection="ids" item="item" index="index" open=" and id in (" close=")">
            #{item}
        </foreach>
    </select>
    <select id="selectByIdMaps">
        select * from biz_activity
        where delete_flag = 1
        <foreach separator="," collection="ids" item="item" index="index" open=" and id in (" close=")">
            #{item}
        </foreach>
        <foreach separator="," collection="ids" item="item" index="index" open=" and delete_flag in (" close=")">
            #{index}
        </foreach>
    </select>
    <update id="deleteById">
        update biz_activity
        set delete_flag = 0
        where id = #{id}
    </update>
    <update id="updateById">
        update biz_activity
        <set>
            <if test="name != nil">name = #{name},</if>
            <if test="pcLink != nil">pc_link = #{pcLink},</if>
            <if test="h5Link != nil">h5_link = #{h5Link},</if>
            <if test="remark != nil">remark = #{remark},</if>
            <if test="createTime != nil">create_time = #{createTime},</if>
            <if test="deleteFlag != nil ">delete_flag = #{deleteFlag},</if>
        </set>
        where id = #{id} and delete_flag = 1
    </update>
    <insert id="insert">
        insert into biz_activity
        <trim prefix="(" suffix=")" suffixOverrides=",">
            <if test="id != nil">id,</if>
            <if test="name != nil">name,</if>
            <if test="pcLink != nil">pc_link,</if>
            <if test="h5Link != nil">h5_link,</if>
            <if test="remark != nil">remark,</if>
            <if test="createTime != nil">create_time,</if>
            <if test="deleteFlag != nil">delete_flag,</if>
        </trim>

        <trim prefix="values (" suffix=")" suffixOverrides=",">
            <if test="id != nil">#{id},</if>
            <if test="name != nil">#{name},</if>
            <if test="pcLink != nil">#{pcLink},</if>
            <if test="h5Link != nil">#{h5Link},</if>
            <if test="remark != nil">#{remark},</if>
            <if test="createTime != nil">#{createTime},</if>
            <if test="deleteFlag != nil">#{deleteFlag},</if>
        </trim>
    </insert>

    <select id="choose" resultMap="BaseResultMap">
        SELECT * FROM biz_activity
        <choose>
            <when test="deleteFlag > 1">WHERE delete_flag > 1</when>
            <when test="deleteFlag == 1">WHERE delete_flag = 1</when>
            <otherwise>WHERE delete_flag = #{deleteFlag}</otherwise>
        </choose>
    </select>

    <sql id="links">
        pc_link,h5_link
        <!--不启用TypeConvert的话，使用${} 而不是 #{}-->
        <if test="column != nil">,${column}</if>
    </sql>

    <select id="selectLinks">
        select
        <include refid="links"/>
        from biz_activity where delete_flag = 1
    </select>
</mapper>
